# Generated by Django 5.2.6 on 2025-09-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("playing_role", models.CharField(max_length=50)),
                ("batting_style", models.CharField(blank=True, max_length=50)),
                ("bowling_style", models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
