# Generated by Django 5.2.6 on 2025-09-08 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "playing_role",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "batting_style",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "bowling_style",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="player_photos/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("venue", models.CharField(max_length=100)),
                ("team1_name", models.CharField(max_length=100)),
                ("team2_name", models.CharField(max_length=100)),
                ("winner_name", models.CharField(blank=True, max_length=100)),
                (
                    "player_of_the_match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BowlingPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overs_bowled", models.FloatField(default=0.0)),
                ("runs_conceded", models.IntegerField(default=0)),
                ("wickets_taken", models.IntegerField(default=0)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.match"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.player"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BattingPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("runs_scored", models.IntegerField(default=0)),
                ("balls_faced", models.IntegerField(default=0)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.match"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.player"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerTournamentStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "matches_played",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("runs_scored", models.IntegerField(blank=True, default=0, null=True)),
                ("balls_faced", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "highest_score",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("not_outs", models.IntegerField(blank=True, default=0, null=True)),
                ("fours", models.IntegerField(blank=True, default=0, null=True)),
                ("sixes", models.IntegerField(blank=True, default=0, null=True)),
                ("fifties", models.IntegerField(blank=True, default=0, null=True)),
                ("hundreds", models.IntegerField(blank=True, default=0, null=True)),
                ("batting_average", models.FloatField(blank=True, null=True)),
                ("batting_strike_rate", models.FloatField(blank=True, null=True)),
                ("overs_bowled", models.FloatField(blank=True, null=True)),
                (
                    "runs_conceded",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "wickets_taken",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("maidens", models.IntegerField(blank=True, default=0, null=True)),
                ("bowling_average", models.FloatField(blank=True, null=True)),
                ("economy_rate", models.FloatField(blank=True, null=True)),
                ("bowling_strike_rate", models.FloatField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.player"
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.tournament"
                    ),
                ),
            ],
        ),
    ]
