# Generated by Django 5.2.6 on 2025-09-05 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_match_bowlingperformance_battingperformance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PlayerTournamentStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matches_played", models.IntegerField(default=0)),
                ("runs_scored", models.IntegerField(default=0)),
                ("balls_faced", models.IntegerField(default=0)),
                ("highest_score", models.IntegerField(default=0)),
                ("batting_average", models.FloatField(default=0.0)),
                ("batting_strike_rate", models.FloatField(default=0.0)),
                ("overs_bowled", models.FloatField(default=0.0)),
                ("runs_conceded", models.IntegerField(default=0)),
                ("wickets_taken", models.IntegerField(default=0)),
                ("bowling_average", models.FloatField(default=0.0)),
                ("economy_rate", models.FloatField(default=0.0)),
                ("bowling_strike_rate", models.FloatField(default=0.0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.player"
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.tournament"
                    ),
                ),
            ],
        ),
    ]
