# Generated by Django 5.2.6 on 2025-09-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_tournament_playertournamentstat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playertournamentstat",
            name="balls_faced",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="playertournamentstat",
            name="batting_average",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playertournamentstat",
            name="batting_strike_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playertournamentstat",
            name="bowling_average",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playertournamentstat",
            name="bowling_strike_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playertournamentstat",
            name="economy_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playertournamentstat",
            name="highest_score",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="playertournamentstat",
            name="matches_played",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="playertournamentstat",
            name="overs_bowled",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playertournamentstat",
            name="runs_conceded",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="playertournamentstat",
            name="runs_scored",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="playertournamentstat",
            name="wickets_taken",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
