# Generated by Django 5.2.6 on 2025-09-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_playertournamentstat_balls_faced_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playertournamentstat",
            name="fifties",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="playertournamentstat",
            name="fours",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="playertournamentstat",
            name="hundreds",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="playertournamentstat",
            name="maidens",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="playertournamentstat",
            name="not_outs",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="playertournamentstat",
            name="sixes",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="playertournamentstat",
            name="team_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="batting_style",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="bowling_style",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="playing_role",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
